services:
  api: 
    build: ./api
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}

  redis:
    image: redis:7-alpine 
    container_name: bda_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: bda_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

      #inyeccion de scripts 
      - ./00_Schema_C3.sql:/docker-entrypoint-initdb.d/00_Schema_C3.sql
      - ./backend/01_procedures.sql:/docker-entrypoint-initdb.d/01_procedures.sql
      - ./backend/02_triggers.sql:/docker-entrypoint-initdb.d/02_triggers.sql
      - ./backend/03_views.sql:/docker-entrypoint-initdb.d/03_views.sql
      - ./backend/04_roles_y_permisos.sql:/docker-entrypoint-initdb.d/04_roles_y_permisos.sql
      - ./backend/05_rls.sql:/docker-entrypoint-initdb.d/05_rls.sql
      - ./backend/06_function.sql:/docker-entrypoint-initdb.d/06_function.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  postgres_data: